{
 "title": "sensors",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "HYG - Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/HYG",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "temperature" }
     ]
    }
   ]
  },
  {
   "title": "THE - temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/THE",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "temperature" }
     ]
    }
   ]
  },
  {
   "title": "BAR - temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/BAR",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "temperature" }
     ]
    }
   ]
  },
  {
   "title": "HYG - humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/HYG",
     "query": "SELECT mean(\"value\") FROM \"/HYG\" WHERE (\"type\" = 'humidity') AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "humidity" }
     ]
    }
   ]
  },
  {
   "title": "BAR - pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/BAR",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pressure" }
     ]
    }
   ]
  },
  {
   "title": "ULT - Distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/ULT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "distance" }
     ]
    }
   ]
  },
  {
   "title": "MAG - magnetometer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "alias": "x",
     "groupBy": [
      { "params": [ "7s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/MAG",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "x" }
     ]
    },
    {
     "alias": "y",
     "groupBy": [
      { "params": [ "7s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/MAG",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "y" }
     ]
    },
    {
     "alias": "z",
     "groupBy": [
      { "params": [ "7s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/MAG",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "z" }
     ]
    }
   ]
  },
  {
   "title": "GAS - LPG",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "7s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/GAS",
     "query": "SELECT mean(\"value\") FROM \"/GAS\" WHERE (\"type\" = 'LPG') AND $timeFilter GROUP BY time(7s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "LPG" }
     ]
    }
   ]
  },
  {
   "title": "GAS - Carbon Monoxide",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "7s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/GAS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "CO" }
     ]
    }
   ]
  },
  {
   "title": "GAS - Smoke",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "7s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/GAS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "CO2" }
     ]
    }
   ]
  }
 ]
}